### PR TITLE
Remove jupyter_server version pin

### PR DESCRIPTION
**Pull request by brian-rose**
This cookbook is encountering [some build problems on the binder](https://github.com/ProjectPythia/na-cordex-viz-cookbook/actions/runs/5415633740/jobs/9844222612#step:17:390)

Removing this obsolete version pin might help.

### CODE REVIEW

**Comment by brian-rose** [comment]
We just got a notice that Jetstream2 (which runs the Pythia binder) is down today. That probably explains the current failure. I'll trigger this again later once JS2 is back online.

**Comment by brian-rose** [comment]
So it turns out this is actually failing because of a bug in our workflows that I just discovered (https://github.com/ProjectPythia/cookbook-actions/issues/79) that affects some PRs that include a change in the environment file.

I will merge this change since it brings this cookbook's environment up to date with the latest template. If there are any further problems with the build (aside from the expected link check failure) we'll figure those out before making a first release of this Cookbook.

**Comment by bonnland** [comment]
Just noticed that the changed line may have a typo?

**Comment by brian-rose** [comment]
> Just noticed that the changed line may have a typo?

Yep I caught that too! Just pushed a fix. Thanks!

**Pull request merged**
