### PR TITLE
doi infrastructure

### PR DESCRIPTION
**Pull request by jukent**
Thank you for your Cookbook contribution!

This PR follows the steps from this [Google Doc on adding DOIs](https://docs.google.com/document/d/1vXXMqiDhB6f3j5TemSp9HouMglXlexdwN6KZCisFkRY/edit).

Link checks will fail on Zenodo badges until first release.

Please add or comment affiliations, ORCIDs, or github usernames for the authors of this book (this is optional).

### CODE REVIEW

**Comment by brian-rose** [comment]
Waiting on #5 before the builds will work again for this repo.

**Review by bonnland — APPROVED** [review]
Thanks for the updates, Julia!   

It doesn't look like the checks are passing right now, so I feel more comfortable letting you merge into main when you feel everything is working and ready.

But if I can help, let me know!

**Comment by brian-rose** [comment]
Doing a "close and reopen" here to see if the build is working.

The link-checker failures are expected and will be resolved after the first release.

**Comment by brian-rose** [comment]
Building successfully and looks good! Merging now.

**Pull request merged**
