### PR TITLE
Remove viz notebook for env testing

### PR DESCRIPTION
**Pull request by brian-rose**
Not for merging!

Just seeing if we can build the environment, run the template notebook, and generate a preview.

### CODE REVIEW

**Comment by brian-rose** [comment]
@bonnland looks like you'll have to approve the workflows before the tests will run here.

**Comment by bonnland** [comment]
> @bonnland looks like you'll have to approve the workflows before the tests will run here.

Thanks for digging in on this!

If it helps, I can implement a flag, something like USE_DATA_SUBSET, to reduce the space/time domain for these plots, in case that helps with running them.

**Comment by brian-rose** [comment]
The build worked here. The preview is not appearing, not sure why, but it's possible that you will need to manually enable GitHub Pages for this repo.

I suspect the build problem is stemming from the kernel_spec in your notebook. I'll see if I can reproduce the same problem in just the template notebook.

**Comment by bonnland** [comment]
> I suspect the build problem is stemming from the kernel_spec in your notebook. I'll see if I can reproduce the same problem in just the template notebook.

I hadn't considered that a possibility.   The jupyterhub at NCAR calls the environment "conda-env-miniconda3-na-cordex-viz-cookbook-dev-py", and initially I thought that didn't make a lot of sense outside of perhaps the NCAR jupyterhub configuration.   

I will try checking in that change to the kernelspec, going with the NCAR jupyterhub choice; maybe it will make a difference!

EDIT:  Changing the kernelspec string to my best second guess did not work either.    Can you verify that it works for you to change the template notebook's kernelspec to the name appearing in environment.yml file (i.e., "cookbook-dev")?   It looks like the kernelspec for the template notebook is currently named "python3".   Shouldn't the notebook's kernelspec match what the environment.yml file uses to name the custom environment?

**Comment by brian-rose** [comment]
> Shouldn't the notebook's kernelspec match what the environment.yml file uses to name the custom environment?

Turns out the answer is no.

In my last push I changed the kernelspec name in the template cookbook to `na-cordex-viz-cookbook-dev` to match what's in the `environment.yml` file.

You can see [in the build log](https://github.com/NCAR/na-cordex-viz-cookbook/actions/runs/4893557807/jobs/8736658781?pr=2#step:17:29) that we triggered the same error as in https://github.com/ProjectPythia/cookbook-template/issues/114.

```
Exception occurred:
[29](https://github.com/NCAR/na-cordex-viz-cookbook/actions/runs/4893557807/jobs/8736658781?pr=2#step:17:30)
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.11/site-packages/jupyter_client/kernelspec.py", line 287, in get_kernel_spec
[30](https://github.com/NCAR/na-cordex-viz-cookbook/actions/runs/4893557807/jobs/8736658781?pr=2#step:17:31)
    raise NoSuchKernel(kernel_name)
[31](https://github.com/NCAR/na-cordex-viz-cookbook/actions/runs/4893557807/jobs/8736658781?pr=2#step:17:32)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named na-cordex-viz-cookbook-dev
```

I guess I don't really understand how the Jupyter server is interpreting those kernelspec fields. I know that in Cookbook work we've always just left them as default values and things work.

**Comment by bonnland** [comment]
> I guess I don't really understand how the Jupyter server is interpreting those kernelspec fields. I know that in Cookbook work we've always just left them as default values and things work.

Thanks for that!  I've always thought that jupyterlab allows multiple environments to exist at the same time, and kernelspec is used to choose the environment for running the notebook.   It seems at least possible that the template's notebook is generic enough for a simple "python3" environment to work with it.   A better test of the infrastructure might be to include some library call in the template notebook that requires a pre-installed package library.

I will try reverting the kernelspec value in the na-cordex-viz notebook to "python3", which I understand to be the default.

**Comment by bonnland** [comment]
@brian-rose  I was able to get the build to work for the na-cordex-viz notebook.   I used the kernelspec of "python3" and made a number of other changes, so I'm not sure exactly which changes were important. 

One change I made was in the _config.yml file, where I set "execute_notebooks: force" instead of using "cache" or "binder".   I looked at the documentation link in _config.yml and noticed that "binder" is not mentioned as a possible option for this setting.

I might suggest finding out if "execute_notebooks: binder" works for you.   Since it's not a documented setting, it seems worth double-checking.   

Thanks for your help!

**Comment by brian-rose** [comment]
> @brian-rose I was able to get the build to work for the na-cordex-viz notebook. I used the kernelspec of "python3" and made a number of other changes, so I'm not sure exactly which changes were important.

That's great! And consistent with the testing that I've done. I don't think we have set a custom kernelspec in any of our existing Cookbooks. For example, [this line in the HRRR-AWS cookbook](https://github.com/ProjectPythia/HRRR-AWS-cookbook/blob/64814f567b0d8c6bd487f0af335b12907bd0c29d/notebooks/example-workflows/2mT.ipynb#L2505) has the default `"name": "python3"`.

**Comment by brian-rose** [comment]
> One change I made was in the _config.yml file, where I set "execute_notebooks: force" instead of using "cache" or "binder". I looked at the documentation link in _config.yml and noticed that "binder" is not mentioned as a possible option for this setting.

That's because the `binder` option is not a standard JupyterBook option. It's a custom feature of the Pythia build workflow that overrides the JupyterBook options. If you want to see the logic for this, it's in [the build-book.yaml reusable workflow here](https://github.com/ProjectPythia/cookbook-actions/blob/main/.github/workflows/build-book.yaml)

**Comment by bonnland** [comment]
OK, good to know!  

I just confirmed that the build goes from success to failure when I switch from  "execute_notebooks: force" to  "execute_notebooks: binder".   Perhaps it's this particular notebook asking for too many resources from the binder service.  

As an experiment, I reduced the number of workers from 20 to 2, and I reduced the memory per worker from 10GB to 2GB.   With this configuration, setting to "binder" fails, and setting to "forced" appears to succeed.   The error message appears to be a failed "git reset" command.

**Comment by brian-rose** [comment]
Closing as this is obsolete now.

**Pull request closed without merging**
