### PR TITLE
Update

### PR DESCRIPTION
**Pull request by brian-rose**
This PR brings the repo up to speed with some recent changes in the Cookbook Template, most importantly the link to the new Pythia Binder.

Switching notebook execution over to the Binder to see if it works!

### CODE REVIEW

**Comment by brian-rose** [comment]
The binder-based build is erroring out with 
```
asyncio.exceptions.TimeoutError
```

I was able to run the whole notebook interactively on the Binder. The longest cell took about 3.5 minutes to execute. We must have a shorter timeout restriction. I will check this out.

**Comment by brian-rose** [comment]
Working now!

**Comment by brian-rose** [comment]
@bonnland take a look at the preview linked above and make sure everything looks correct, then I think we're ready to merge this.

**Comment by bonnland** [comment]
The preview looks good!   Go ahead and merge when convenient.

**Pull request merged**
